In [1]:
import numpy as np
import pandas as pd

In [2]:
hr_train = pd.read_csv(r'train_hr.csv',index_col=0,header=0)
hr_train.head()

department     region         education gender  \
employee_id                                                          
65438        Sales & Marketing   region_7  Master's & above      f   
65141               Operations  region_22        Bachelor's      m   
7513         Sales & Marketing  region_19        Bachelor's      m   
2542         Sales & Marketing  region_23        Bachelor's      m   
48945               Technology  region_26        Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [3]:
hr_train.shape

(54808, 13)

In [4]:
hr_train.drop("gender",axis=1,inplace=True)
hr_train.shape

(54808, 12)

In [5]:
hr_train.isnull().sum()

department                 0
region                     0
education               2409
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [6]:
hr_train["education"].fillna(hr_train["education"].mode()[0],inplace=True) 
hr_train["previous_year_rating"].fillna(0,inplace=True) ## previous year of employee dont exist as they were recruited current year so replacing with zero

In [7]:
hr_train["education"].mode()[0]

"Bachelor's"

In [8]:
hr_train.isnull().sum()

department              0
region                  0
education               0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [9]:
## categorical var
colname = ['department',
'region', 'education',
'recruitment_channel']
colname

['department', 'region', 'education', 'recruitment_channel']

In [10]:
# For preprocessing the data converting cat data into num
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
    hr_train[x]=le.fit_transform(hr_train[x])

In [11]:
hr_train.head()

department  region  education  recruitment_channel  \
employee_id                                                       
65438                 7      31          2                    2   
65141                 4      14          0                    0   
7513                  7      10          0                    2   
2542                  7      15          0                    0   
48945                 8      18          0                    0   

             no_of_trainings  age  previous_year_rating  length_of_service  \
employee_id                                                                  
65438                      1   35                   5.0                  8   
65141                      1   30                   5.0                  4   
7513                       1   34                   3.0                  7   
2542                       2   39                   1.0                 10   
48945                      1   45                   3.0                  2   

             KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
employee_id                                                               
65438                    1            0                  49            0  
65141                    0            0                  60            0  
7513                     0            0                  50            0  
2542                     0            0                  50            0  
48945                    0            0                  73            0

In [12]:
X = hr_train.values[:,:-1]
Y = hr_train.values[:,-1]

In [13]:
X.shape

(54808, 11)

In [14]:
Y.shape

(54808,)

In [15]:
## scaling is must in deep learning
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
#print(X)

In [16]:
hr_train.dtypes

department                int32
region                    int32
education                 int32
recruitment_channel       int32
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted               int64
dtype: object

In [17]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
random_state=10)

In [18]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)
## print(list(zip(Y_test,Y_pred)))

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
print("Classification report: ")
print()
print(classification_report(Y_test,Y_pred))
print()
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14994    70]
 [ 1285    94]]

Classification report: 

              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.57      0.07      0.12      1379

    accuracy                           0.92     16443
   macro avg       0.75      0.53      0.54     16443
weighted avg       0.89      0.92      0.89     16443


Accuracy of the model:  0.9175941129964118


In [20]:
## predicting using KNeighors_Classifer
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors = int(np.sqrt(len(X_train))),metric = 'euclidean')
## fit the model on the data and predict the values
model_knn.fit(X_train,Y_train)
Y_pred = model_knn.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.

In [21]:
np.sqrt(len(X_train))

195.86985475054604

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[15042    22]
 [ 1284    95]]

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.81      0.07      0.13      1379

    accuracy                           0.92     16443
   macro avg       0.87      0.53      0.54     16443
weighted avg       0.91      0.92      0.89     16443

Accuracy of the model:  0.9205741044821505


In [23]:
from sklearn.svm import SVC
svc_model = SVC(kernel='rbf',C=1.0,gamma=0.1)
svc_model.fit(X_train,Y_train)
Y_pred = svc_model.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[15044    20]
 [ 1240   139]]

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.87      0.10      0.18      1379

    accuracy                           0.92     16443
   macro avg       0.90      0.55      0.57     16443
weighted avg       0.92      0.92      0.89     16443

Accuracy of the model:  0.9233716475095786


In [25]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14096   968]
 [  763   616]]

Classification report: 
              precision    recall  f1-score   support

         0.0       0.95      0.94      0.94     15064
         1.0       0.39      0.45      0.42      1379

    accuracy                           0.89     16443
   macro avg       0.67      0.69      0.68     16443
weighted avg       0.90      0.89      0.90     16443

Accuracy of the model:  0.8947272395548258


In [27]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14958   106]
 [  962   417]]

Classification report: 
              precision    recall  f1-score   support

         0.0       0.94      0.99      0.97     15064
         1.0       0.80      0.30      0.44      1379

    accuracy                           0.94     16443
   macro avg       0.87      0.65      0.70     16443
weighted avg       0.93      0.94      0.92     16443

Accuracy of the model:  0.9350483488414523


### upsampling

In [29]:
hr_train.is_promoted.value_counts() ### imbalanced dataset

0    50140
1     4668
Name: is_promoted, dtype: int64

In [30]:
from sklearn.utils import resample
# Separate majority and minority classes
df_majority = hr_train[hr_train.is_promoted==0]
df_minority = hr_train[hr_train.is_promoted==1]

# Upsample minority class
df_minority_upsampled = resample(df_minority,  ## on data we have to sample         /  wheras in downsampling it would be df_majority
                                replace=True, # sample with replacement reandomly  /  replace = false as we dont have to select random sample from it
                                n_samples=50140, # to match majority class        /   n_samples = 4668
                                random_state=10) # reproducible results

# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

# Display new class counts
df_upsampled.is_promoted.value_counts()

1    50140
0    50140
Name: is_promoted, dtype: int64

In [31]:
X = df_upsampled.values[:,:-1]
Y = df_upsampled.values[:,-1]

In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
#print(X)

In [33]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
random_state=10)

In [34]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[13955  1060]
 [    0 15069]]

Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      0.93      0.96     15015
         1.0       0.93      1.00      0.97     15069

    accuracy                           0.96     30084
   macro avg       0.97      0.96      0.96     30084
weighted avg       0.97      0.96      0.96     30084

Accuracy of the model:  0.9647653237601382


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14410   605]
 [    0 15069]]

Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98     15015
         1.0       0.96      1.00      0.98     15069

    accuracy                           0.98     30084
   macro avg       0.98      0.98      0.98     30084
weighted avg       0.98      0.98      0.98     30084

Accuracy of the model:  0.9798896423347959


In [38]:
hr_test = pd.read_csv(r'test_hr.csv',index_col=0,header = 0)
hr_test.head()

department     region   education gender  \
employee_id                                                    
8724                Technology  region_26  Bachelor's      m   
74430                       HR   region_4  Bachelor's      f   
72255        Sales & Marketing  region_13  Bachelor's      m   
38562              Procurement   region_2  Bachelor's      f   
64486                  Finance  region_29  Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
8724                   sourcing                1   24                   NaN   
74430                     other                1   31                   3.0   
72255                     other                1   31                   1.0   
38562                     other                3   31                   2.0   
64486                  sourcing                1   30                   4.0   

             length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
employee_id                                                                     
8724                         1              1            0                  77  
74430                        5              0            0                  51  
72255                        4              0            0                  47  
38562                        9              0            0                  65  
64486                        7              0            0                  61

In [39]:
hr_test.shape

(23490, 12)

In [40]:
hr_test.drop('gender',axis=1,inplace=True)

In [41]:
hr_test.isnull().sum()

department                 0
region                     0
education               1034
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [42]:
hr_test['education'].fillna(hr_test['education'].mode()[0],inplace=True)

In [43]:
hr_test['education'].mode()[0]

"Bachelor's"

In [44]:
hr_test['previous_year_rating'].fillna(0,inplace=True)

In [45]:
hr_test.isnull().sum()

department              0
region                  0
education               0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [46]:
colname = ['department',
'region', 'education',
'recruitment_channel']
colname

['department', 'region', 'education', 'recruitment_channel']

In [47]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for x in colname:
    hr_test[x]=le.fit_transform(hr_test[x])

In [48]:
hr_test.head()

department  region  education  recruitment_channel  \
employee_id                                                       
8724                  8      18          0                    2   
74430                 2      28          0                    0   
72255                 7       4          0                    0   
38562                 5      11          0                    0   
64486                 1      21          0                    2   

             no_of_trainings  age  previous_year_rating  length_of_service  \
employee_id                                                                  
8724                       1   24                   0.0                  1   
74430                      1   31                   3.0                  5   
72255                      1   31                   1.0                  4   
38562                      3   31                   2.0                  9   
64486                      1   30                   4.0                  7   

             KPIs_met >80%  awards_won?  avg_training_score  
employee_id                                                  
8724                     1            0                  77  
74430                    0            0                  51  
72255                    0            0                  47  
38562                    0            0                  65  
64486                    0            0                  61

In [49]:
X_test_new=hr_test

In [50]:
X_test_new = scaler.transform(X_test_new)

In [51]:
hr_test.dtypes

department                int32
region                    int32
education                 int32
recruitment_channel       int32
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
dtype: object

In [52]:
Y_pred = model_RandomForest.predict(X_test_new)

In [53]:
Y_pred

array([0., 0., 0., ..., 0., 0., 1.])

In [54]:
Y_pred = Y_pred.astype(int)

In [55]:
test_data = pd.read_csv(r'test_hr.csv')
test_data['Y_predictions'] = Y_pred
test_data.head()

employee_id         department     region   education gender  \
0         8724         Technology  region_26  Bachelor's      m   
1        74430                 HR   region_4  Bachelor's      f   
2        72255  Sales & Marketing  region_13  Bachelor's      m   
3        38562        Procurement   region_2  Bachelor's      f   
4        64486            Finance  region_29  Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24                   NaN   
1               other                1   31                   3.0   
2               other                1   31                   1.0   
3               other                3   31                   2.0   
4            sourcing                1   30                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  1              1            0                  77   
1                  5              0            0                  51   
2                  4              0            0                  47   
3                  9              0            0                  65   
4                  7              0            0                  61   

   Y_predictions  
0              0  
1              0  
2              0  
3              0  
4              0

In [56]:
test_data.Y_predictions=test_data.Y_predictions.map({1:"Promoted",0:"Not Promoted"})
test_data.head()

employee_id         department     region   education gender  \
0         8724         Technology  region_26  Bachelor's      m   
1        74430                 HR   region_4  Bachelor's      f   
2        72255  Sales & Marketing  region_13  Bachelor's      m   
3        38562        Procurement   region_2  Bachelor's      f   
4        64486            Finance  region_29  Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24                   NaN   
1               other                1   31                   3.0   
2               other                1   31                   1.0   
3               other                3   31                   2.0   
4            sourcing                1   30                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  1              1            0                  77   
1                  5              0            0                  51   
2                  4              0            0                  47   
3                  9              0            0                  65   
4                  7              0            0                  61   

  Y_predictions  
0  Not Promoted  
1  Not Promoted  
2  Not Promoted  
3  Not Promoted  
4  Not Promoted

In [57]:
test_data.to_excel("HR Analytics Result.xlsx")

In [58]:
test_data.Y_predictions.value_counts()

Not Promoted    21849
Promoted         1641
Name: Y_predictions, dtype: int64

In [59]:
test_data.shape

(23490, 14)

## ANN MLP classifier

In [60]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(100),max_iter=100, early_stopping=True,n_iter_no_change=5,
                    random_state=10, activation="relu", solver="adam",learning_rate="constant",
                    learning_rate_init=0.01,verbose=True)
mlp.fit(X_train,Y_train)
Y_pred = mlp.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

Iteration 1, loss = 0.49353556
Validation score: 0.759687
Iteration 2, loss = 0.44496514
Validation score: 0.787892
Iteration 3, loss = 0.41774846
Validation score: 0.799288
Iteration 4, loss = 0.39958101
Validation score: 0.796724
Iteration 5, loss = 0.38543961
Validation score: 0.811538
Iteration 6, loss = 0.37606174
Validation score: 0.818091
Iteration 7, loss = 0.36970200
Validation score: 0.811254
Iteration 8, loss = 0.36471271
Validation score: 0.817664
Iteration 9, loss = 0.36296416
Validation score: 0.803561
Iteration 10, loss = 0.36004489
Validation score: 0.813960
Iteration 11, loss = 0.35759419
Validation score: 0.813675
Iteration 12, loss = 0.35636087
Validation score: 0.818234
Iteration 13, loss = 0.35492332
Validation score: 0.820228
Iteration 14, loss = 0.35287140
Validation score: 0.820228
Iteration 15, loss = 0.35227568
Validation score: 0.822222
Iteration 16, loss = 0.35042860
Validation score: 0.818661
Iteration 17, loss = 0.34996458
Validation score: 0.811681
Iterat

In [61]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[10788  4227]
 [  910 14159]]

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      0.72      0.81     15015
         1.0       0.77      0.94      0.85     15069

    accuracy                           0.83     30084
   macro avg       0.85      0.83      0.83     30084
weighted avg       0.85      0.83      0.83     30084

Accuracy of the model:  0.8292447812790852


In [62]:
from sklearn.neural_network import MLPClassifier

mlp_gs = MLPClassifier(max_iter=100,early_stopping=True,n_iter_no_change=5,
                        random_state=10,learning_rate_init=0.01,learning_rate= 'constant',
                        verbose=True )
parameter_space = {
            'hidden_layer_sizes': [(12,12,12),(10,10)],
            'activation': ['tanh', 'relu'],
            'solver': ['sgd', 'adam'],
            'alpha': [0.0001, 0.01]
}

from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(mlp_gs, parameter_space, n_jobs=-1, cv=5)  ## n_jobs = -1 uses every processor system works faster

In [63]:
clf.fit(X_train,Y_train)

Iteration 1, loss = 0.50036045
Validation score: 0.774644
Iteration 2, loss = 0.41293006
Validation score: 0.810969
Iteration 3, loss = 0.38576882
Validation score: 0.812821
Iteration 4, loss = 0.37153351
Validation score: 0.814957
Iteration 5, loss = 0.36771607
Validation score: 0.816097
Iteration 6, loss = 0.36586634
Validation score: 0.820655
Iteration 7, loss = 0.36278737
Validation score: 0.821510
Iteration 8, loss = 0.36018440
Validation score: 0.817949
Iteration 9, loss = 0.35898431
Validation score: 0.819801
Iteration 10, loss = 0.35834264
Validation score: 0.821083
Iteration 11, loss = 0.35790253
Validation score: 0.819516
Iteration 12, loss = 0.35586844
Validation score: 0.822365
Iteration 13, loss = 0.35558282
Validation score: 0.819231
Iteration 14, loss = 0.35517769
Validation score: 0.822080
Iteration 15, loss = 0.35401783
Validation score: 0.823362
Iteration 16, loss = 0.35392931
Validation score: 0.823077
Iteration 17, loss = 0.35348483
Validation score: 0.819801
Iterat

GridSearchCV(cv=5,
             estimator=MLPClassifier(early_stopping=True,
                                     learning_rate_init=0.01, max_iter=100,
                                     n_iter_no_change=5, random_state=10,
                                     verbose=True),
             n_jobs=-1,
             param_grid={'activation': ['tanh', 'relu'],
                         'alpha': [0.0001, 0.01],
                         'hidden_layer_sizes': [(12, 12, 12), (10, 10)],
                         'solver': ['sgd', 'adam']})

In [64]:
print('Best parameters found :\n',clf.best_params_)

Best parameters found :
 {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (12, 12, 12), 'solver': 'adam'}


In [65]:
Y_pred = clf.predict(X_test)