In [1]:
import numpy as np
import pandas as pd
training_data=pd.read_excel(r'Titanic_Survival_train.xls',index_col=0,header=0)
testing_data=pd.read_excel(r'Titanic_Survival_test.xls',index_col=0,header=0)
print(training_data.shape)
print(testing_data.shape)

(891, 11)
(21, 11)


In [2]:
training_data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [3]:
testing_data.head()

Survived  Pclass  \
PassengerId                     
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   

                                                         Name     Sex   Age  \
PassengerId                                                                   
871                                         Balkic, Mr. Cerin    male  26.0   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0   
873                                  Carlsson, Mr. Frans Olof    male  33.0   
874                               Vander Cruyssen, Mr. Victor    male  47.0   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0   

             SibSp  Parch     Ticket     Fare        Cabin Embarked  
PassengerId                                                          
871              0      0     349248   7.8958          NaN        S  
872              1      1      11751  52.5542          D35        S  
873              0      0        695   5.0000  B51 B53 B55        S  
874              0      0     345765   9.0000          NaN        S  
875              1      0  P/PP 3381  24.0000          NaN        C

In [4]:
## feature selection
training_data = training_data[['Name','Pclass','Sex','Age','Survived']]
testing_data = testing_data[['Name','Pclass','Sex','Age','Survived']]
print(training_data.shape)
print(testing_data.shape)

(891, 5)
(21, 5)


In [5]:
## finding the missing values
print(training_data.isnull().sum())
print(testing_data.isnull().sum())

Name          0
Pclass        0
Sex           0
Age         177
Survived      0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         2
Survived    0
dtype: int64


In [8]:
## imputing numerical missing values with mean
training_data['Age'].fillna(int(training_data['Age'].mean()),inplace=True) ## we used int as there are babies in titanic data with age in months
testing_data['Age'].fillna(int(testing_data['Age'].mean()),inplace=True)

In [7]:
print(training_data.isnull().sum())
print(testing_data.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


In [10]:
## transforming categorical to numerical ( can use label encoder or map function)
from sklearn import preprocessing
colname = ['Sex']
le=preprocessing.LabelEncoder()
for x in colname:
    training_data[x]=le.fit_transform(training_data[x])
    testing_data[x]=le.fit_transform(testing_data[x])


In [15]:
training_data.head()

Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   

              Age  Survived  
PassengerId                  
1            22.0         0  
2            38.0         1  
3            26.0         1  
4            35.0         1  
5            35.0         0

In [14]:
testing_data.head()

Name  Pclass  Sex  \
PassengerId                                                                  
871                                         Balkic, Mr. Cerin       3    1   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)       1    0   
873                                  Carlsson, Mr. Frans Olof       1    1   
874                               Vander Cruyssen, Mr. Victor       3    1   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)       2    0   

              Age  Survived  
PassengerId                  
871          26.0         0  
872          47.0         1  
873          33.0         0  
874          47.0         0  
875          28.0         1

In [ ]:
## training_data['Sex']=training_data['Sex'].map({'female':0,'male':1})
## testing_data['Sex']=testing_data['Sex'].map({'female':0,'male':1})

In [16]:
X_train = training_data.values[:870,1:-1] ## as we have to take obs from 0 to 869 that means 870 obs 
Y_train = training_data.values[:870,-1]
Y_train=Y_train.astype(int) ## to avoid error of unknown label unknown

X_test = testing_data.values[:,1:-1] #### from 871 obs to last obs 
Y_test = testing_data.values[:,-1]
Y_test = Y_test.astype(int)

In [17]:
X_train.shape

(870, 3)

In [18]:
Y_train.shape

(870,)

In [19]:
X_test.shape

(21, 3)

In [20]:
Y_test.shape

(21,)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
##while working on separate train and test data, fit the scaler object only upon the train data
#and use the same scaler object to transform both the train as well as the test data.

In [25]:
## predicting using KNeighors_Classifer
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors = int(np.sqrt(len(X_train))),metric = 'euclidean')
## fit the model on the data and predict the values
model_knn.fit(X_train,Y_train)
Y_pred = model_knn.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 0), (0, 0)]


In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[12  2]
 [ 2  5]]

Classification report: 
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        14
           1       0.71      0.71      0.71         7

    accuracy                           0.81        21
   macro avg       0.79      0.79      0.79        21
weighted avg       0.81      0.81      0.81        21

Accuracy of the model:  0.8095238095238095


In [28]:
## selecting best value for k
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    model_KNN = KNeighborsClassifier(n_neighbors=K,metric="euclidean")
    model_KNN.fit(X_train, Y_train)
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is  0.8571428571428571 for K-Value: 1
Accuracy is  0.8571428571428571 for K-Value: 2
Accuracy is  0.8571428571428571 for K-Value: 3
Accuracy is  0.9047619047619048 for K-Value: 4
Accuracy is  0.9047619047619048 for K-Value: 5
Accuracy is  0.9047619047619048 for K-Value: 6
Accuracy is  0.8571428571428571 for K-Value: 7
Accuracy is  0.8571428571428571 for K-Value: 8
Accuracy is  0.8095238095238095 for K-Value: 9
Accuracy is  0.8571428571428571 for K-Value: 10
Accuracy is  0.8571428571428571 for K-Value: 11
Accuracy is  0.9047619047619048 for K-Value: 12
Accuracy is  0.8571428571428571 for K-Value: 13
Accuracy is  0.9047619047619048 for K-Value: 14
Accuracy is  0.8571428571428571 for K-Value: 15
Accuracy is  0.8571428571428571 for K-Value: 16
Accuracy is  0.8571428571428571 for K-Value: 17
Accuracy is  0.8095238095238095 for K-Value: 18
Accuracy is  0.8095238095238095 for K-Value: 19
Accuracy is  0.7619047619047619 for K-Value: 20
Accuracy is  0.8095238095238095 for K-Value: 21
A

In [36]:
for k in my_dict:
    if my_dict[k] ==max(my_dict.values()):
        print(k,':', my_dict[k])
    

4 : 0.9047619047619048
5 : 0.9047619047619048
6 : 0.9047619047619048
12 : 0.9047619047619048
14 : 0.9047619047619048


In [34]:
## predicting using KNeighors_Classifer
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors =14,metric = 'euclidean')
## fit the model on the data and predict the values
model_knn.fit(X_train,Y_train)
Y_pred = model_knn.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[12  2]
 [ 0  7]]

Classification report: 
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

Accuracy of the model:  0.9047619047619048


In [37]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[12  2]
 [ 0  7]]

Classification report: 
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

Accuracy of the model:  0.9047619047619048
